/**
 * brain-3d.js — 3D Brain Explorer (v3, GLTF edition)
 *
 * Loads anatomically-accurate region meshes from data/brain_meshes/*.glb
 * generated by generate_brain_meshes.py (fsaverage5 pial + Destrieux atlas).
 *
 * Exposes window.__brain3d = {
 *   mount(container), unmount(),
 *   setCameraView(name), CAMERA_VIEWS,
 *   highlightRegion(id), dimAllRegions(exceptIds[]), resetRegions(),
 *   regionMeshes, corticalMeshes, subcorticalMeshes,
 *   toggleGlass(bool), setSubcorticalVisible(bool),
 *   ready,   // Promise that resolves when all GLTFs are loaded
 * }
 *
 * Events dispatched on window:
 *   brain3dProgress  { detail: { loaded, total } }
 *   brain3dReady     { detail: { regionCount } }
 */

import * as THREE        from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader }    from 'three/addons/loaders/GLTFLoader.js';

console.log('[brain-3d] Module loaded, Three.js r' + THREE.REVISION);

// ══════════════════════════════════════════════════════════════════════════════
// REGION COLOR MAP
// ══════════════════════════════════════════════════════════════════════════════

const REGION_COLORS = {
  frontal_lobe:         0xE8826E,
  prefrontal_cortex:    0xD4705E,
  brocas_area:          0xC86860,
  motor_cortex:         0xEC7A68,
  parietal_lobe:        0x6EC0B4,
  somatosensory_cortex: 0x60B0A8,
  temporal_lobe:        0x9A90D0,
  wernickes_area:       0x8880C4,
  occipital_lobe:       0xD4B040,
  cingulate_gyrus:      0x9CC488,
  medial_frontal:       0xDC6060,
  // subcortical
  thalamus:             0x98AADE,
  hippocampus:          0xAAC050,
  amygdala:             0xD49060,
  caudate:              0x88A8C4,
  putamen:              0x8090C4,
  globus_pallidus:      0x98AACE,
  brainstem:            0x908070,
  cerebellum:           0x70A8C4,
  // glass shell
  full_hemisphere:      0xE0CCC0,
};

// ══════════════════════════════════════════════════════════════════════════════
// RENDERER
// ══════════════════════════════════════════════════════════════════════════════

var renderer, canvas;
try {
  renderer = new THREE.WebGLRenderer({ antialias: true });
  renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
  renderer.shadowMap.enabled   = true;
  renderer.shadowMap.type      = THREE.PCFSoftShadowMap;
  renderer.toneMapping         = THREE.ReinhardToneMapping;
  renderer.toneMappingExposure = 2.8;
  canvas = renderer.domElement;
  canvas.style.cssText = 'display:block; border-radius:16px; cursor:grab;';
} catch (e) {
  console.error('[brain-3d] WebGL not available:', e.message);
  window.dispatchEvent(new CustomEvent('brain3dNoWebGL'));
  // Stub out window.__brain3d so callers don't crash
  window.__brain3d = { mount:function(){}, unmount:function(){}, setCameraView:function(){},
    highlightRegion:function(){}, dimAllRegions:function(){}, resetRegions:function(){},
    toggleGlass:function(){}, setSubcorticalVisible:function(){},
    regionMeshes:[], corticalMeshes:[], subcorticalMeshes:[],
    ready: Promise.resolve(), CAMERA_VIEWS:{},
    setCsMode:function(){}, setCsSlider:function(){}, setVascTerritory:function(){},
    toggleLesionMode:function(){}, resetLesions:function(){}, activatePathology:function(){},
    clearPathology:function(){}, showPathway:function(){}, hidePathway:function(){}, setPathway:function(){},
    PATHOLOGY_DEFS:{} };
  throw e; // stop module execution — everything below needs renderer
}

// ══════════════════════════════════════════════════════════════════════════════
// SCENE + CAMERA + CONTROLS
// ══════════════════════════════════════════════════════════════════════════════

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x0A0D14);

const camera = new THREE.PerspectiveCamera(40, 1.54, 0.1, 100);
camera.position.set(4.8, 0.5, 0.4);

// Brain centre of mass — matches COORD_OFFSET computed by generate_brain_meshes.py
// so that the loaded GLTFs are already centred here.
const CAM_TARGET = new THREE.Vector3(0.55, 0.05, 0.10);
const controls   = new OrbitControls(camera, canvas);
controls.enableDamping  = true;
controls.dampingFactor  = 0.07;
controls.minDistance    = 2.8;
controls.maxDistance    = 10.0;
controls.enablePan      = false;
controls.target.copy(CAM_TARGET);
controls.update();

// ══════════════════════════════════════════════════════════════════════════════
// LIGHTING  (clinical: cool-white key + blue fill/rim + hemisphere ambient)
// ══════════════════════════════════════════════════════════════════════════════

const keyLight = new THREE.DirectionalLight(0xFFF8F4, 5.0);
keyLight.position.set(-2, 6, 3.5);
keyLight.castShadow = true;
keyLight.shadow.mapSize.setScalar(2048);
scene.add(keyLight);

const fillLight = new THREE.DirectionalLight(0xC4D8FF, 1.5);
fillLight.position.set(5, 0.5, -1.5);
scene.add(fillLight);

const rimLight = new THREE.DirectionalLight(0x90BCFF, 2.5);
rimLight.position.set(1.5, -3, -5);
scene.add(rimLight);

scene.add(new THREE.HemisphereLight(0xB0C8E0, 0x583020, 1.4));
scene.add(new THREE.AmbientLight(0x909898, 0.6));

// ══════════════════════════════════════════════════════════════════════════════
// GYRAL NORMAL MAP  (canvas-generated, tiled over anatomy)
// ══════════════════════════════════════════════════════════════════════════════

function makeGyralNormal(size) {
  size = size || 512;
  var c   = document.createElement('canvas');
  c.width = c.height = size;
  var ctx = c.getContext('2d');
  var img = ctx.createImageData(size, size);

  function h(x, y) {
    return (
      0.55 * Math.sin(x * 0.042 + 0.40) * Math.sin(y * 0.038 + 0.80) +
      0.35 * Math.sin(x * 0.030 + 1.20) * Math.cos(y * 0.044 + 0.30) +
      0.28 * Math.sin(x * 0.092 + 2.10) * Math.sin(y * 0.085 + 1.50) +
      0.15 * Math.sin(x * 0.180 + 0.70) * Math.sin(y * 0.155 + 2.00) +
      0.08 * Math.cos(x * 0.260 + 1.80) * Math.cos(y * 0.220 + 0.60)
    );
  }

  var strength = 1.2;
  var eps      = 1.0;

  for (var y = 0; y < size; y++) {
    for (var x = 0; x < size; x++) {
      var dhdx = (h(x + eps, y) - h(x - eps, y)) / (2 * eps);
      var dhdy = (h(x, y + eps) - h(x, y - eps)) / (2 * eps);
      var nx   = -dhdx * strength;
      var ny   = -dhdy * strength;
      var nz   = 1.0;
      var len  = Math.sqrt(nx * nx + ny * ny + nz * nz);
      var i    = (y * size + x) * 4;
      img.data[i]     = Math.round((nx / len * 0.5 + 0.5) * 255);
      img.data[i + 1] = Math.round((ny / len * 0.5 + 0.5) * 255);
      img.data[i + 2] = Math.round((nz / len * 0.5 + 0.5) * 255);
      img.data[i + 3] = 255;
    }
  }
  ctx.putImageData(img, 0, 0);

  var tex = new THREE.CanvasTexture(c);
  tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
  tex.repeat.set(2.5, 2.5);
  return tex;
}

const GYRAL_NORMAL = makeGyralNormal(512);

// ══════════════════════════════════════════════════════════════════════════════
// BRAIN GROUP + MESH REGISTRIES
// ══════════════════════════════════════════════════════════════════════════════

const brainGroup        = new THREE.Group();
scene.add(brainGroup);

const regionMeshes      = [];    // all clickable region meshes
const corticalMeshes    = [];
const subcorticalMeshes = [];
var   glassMesh         = null;
var   glassVisible      = true;

// Ground shadow plane
var groundMesh = new THREE.Mesh(
  new THREE.PlaneGeometry(10, 10),
  new THREE.ShadowMaterial({ opacity: 0.18 })
);
groundMesh.receiveShadow = true;
groundMesh.rotation.x    = -Math.PI / 2;
groundMesh.position.y    = -1.5;
scene.add(groundMesh);

// Selection state — gold emissive instead of OutlinePass (faster, no extra CDN deps)
var _selectedMeshes = [];

// ══════════════════════════════════════════════════════════════════════════════
// MATERIAL FACTORY
// ══════════════════════════════════════════════════════════════════════════════

function makeMaterial(regionId, type) {
  var color = REGION_COLORS[regionId] || 0x8888AA;

  if (type === 'glass') {
    return new THREE.MeshPhysicalMaterial({
      color:       new THREE.Color(color),
      roughness:   0.10,
      metalness:   0.00,
      transparent: true,
      opacity:     0.08,
      depthWrite:  false,
      side:        THREE.DoubleSide,
    });
  }

  // Cortical and subcortical regions
  var col = new THREE.Color(color);
  var mat = new THREE.MeshStandardMaterial({
    color:             col,
    roughness:         0.55,
    metalness:         0.05,
    emissive:          col,
    emissiveIntensity: 0.12,
    side:              THREE.DoubleSide,
  });
  mat._origColor = col.clone();
  return mat;
}

// ══════════════════════════════════════════════════════════════════════════════
// GLTF LOADING
// ══════════════════════════════════════════════════════════════════════════════

const loader = new GLTFLoader();

function loadGLTFRegion(regionId, entry) {
  return new Promise(function(resolve, reject) {
    loader.load(
      entry.file,
      function(gltf) {
        var mat      = makeMaterial(regionId, entry.type);
        var meshList = [];

        gltf.scene.traverse(function(child) {
          if (child.isMesh) {
            child.material      = mat;
            child.name          = regionId;
            child.castShadow    = (entry.type !== 'glass');
            child.receiveShadow = (entry.type !== 'glass');
            child.userData      = { regionId: regionId, label: regionId, type: entry.type };
            meshList.push(child);
          }
        });

        if (meshList.length === 0) {
          reject(new Error('No mesh found in ' + entry.file));
          return;
        }

        brainGroup.add(gltf.scene);
        var primaryMesh = meshList[0];

        if (entry.type === 'glass') {
          glassMesh = primaryMesh;
        } else {
          meshList.forEach(function(m) {
            regionMeshes.push(m);
            if (entry.type === 'subcortical') {
              subcorticalMeshes.push(m);
              m.visible = false;  // hidden until glass toggle reveals them
            } else {
              corticalMeshes.push(m);
            }
          });
        }

        resolve(primaryMesh);
      },
      undefined,
      function(err) { reject(err); }
    );
  });
}

// ── Kick off loading immediately when the module initialises ─────────────────

var _readyResolve = null;
var _readyPromise = new Promise(function(res) { _readyResolve = res; });

async function loadBrain() {
  console.log('[brain-3d] loadBrain() starting');
  var _fired = false;
  function _finish() {
    if (_fired) return;
    _fired = true;
    console.log('[brain-3d] brain3dReady dispatched, regionCount=' + regionMeshes.length);
    window.dispatchEvent(new CustomEvent('brain3dReady', {
      detail: { regionCount: regionMeshes.length }
    }));
    _readyResolve();
  }

  try {
    var manifest;
    try {
      var resp = await fetch('data/brain_regions_manifest.json');
      manifest = await resp.json();
      console.log('[brain-3d] Manifest loaded:', Object.keys(manifest).length, 'regions');
    } catch (e) {
      console.error('[brain-3d] Could not load manifest:', e);
      return;
    }

    var regionIds = Object.keys(manifest);
    var glassId   = regionIds.find(function(id) { return manifest[id].type === 'glass'; });
    var otherIds  = regionIds.filter(function(id) { return manifest[id].type !== 'glass'; });
    var total     = regionIds.length;
    var loaded    = 0;

    function onOne() {
      loaded++;
      window.dispatchEvent(new CustomEvent('brain3dProgress', {
        detail: { loaded: loaded, total: total }
      }));
    }

    // Glass brain first — renders as transparent shell immediately
    if (glassId) {
      try {
        await loadGLTFRegion(glassId, manifest[glassId]);
        onOne();
      } catch (e) {
        console.warn('[brain-3d] Glass brain load failed:', e);
        loaded++;
      }
    }

    // All other regions in parallel
    await Promise.allSettled(
      otherIds.map(function(id) {
        return loadGLTFRegion(id, manifest[id])
          .then(onOne)
          .catch(function(e) {
            console.warn('[brain-3d] Region load failed (' + id + '):', e);
            onOne();
          });
      })
    );
  } catch (e) {
    console.error('[brain-3d] Unexpected error in loadBrain:', e);
  } finally {
    _finish();
  }
}

loadBrain();

// ══════════════════════════════════════════════════════════════════════════════
// INTERACTION — hover emissive + click gold outline
// ══════════════════════════════════════════════════════════════════════════════

var raycaster    = new THREE.Raycaster();
var mouse        = new THREE.Vector2(-10, -10);
var hoveredMesh  = null;
var selectedMesh = null;

function _restoreColor(mesh) {
  if (mesh && mesh.material._origColor) {
    mesh.material.color.copy(mesh.material._origColor);
  }
}

function _setEmissive(mesh, hexColor, intensity) {
  var m = mesh.material;
  if (m.emissive) {
    m.emissive.set(hexColor);
    m.emissiveIntensity = intensity;
  } else {
    m.color.set(hexColor);
  }
}

function setHover(mesh) {
  if (hoveredMesh === mesh) return;
  if (hoveredMesh && hoveredMesh !== selectedMesh) {
    _restoreColor(hoveredMesh);
    if (hoveredMesh.material.emissive) hoveredMesh.material.emissiveIntensity = 0.12;
  }
  hoveredMesh = mesh;
  if (hoveredMesh && hoveredMesh !== selectedMesh) {
    _setEmissive(hoveredMesh, 0xffffff, 0.30);
  }
  if (window.__brainUI && window.__brainUI.hoverRegion) {
    window.__brainUI.hoverRegion(mesh ? mesh.userData.regionId : null);
  }
}

function selectRegion(mesh) {
  if (selectedMesh === mesh) return;
  if (selectedMesh) {
    _restoreColor(selectedMesh);
    if (selectedMesh.material.emissive) selectedMesh.material.emissiveIntensity = 0.12;
  }
  selectedMesh = mesh;
  if (!mesh) return;
  _setEmissive(mesh, 0xffd080, 0.45);
  if (window.__brainUI) window.__brainUI.openRegion(mesh.userData.regionId);
}

// ══════════════════════════════════════════════════════════════════════════════
// CAMERA PRESET VIEWS
// ══════════════════════════════════════════════════════════════════════════════

var CAMERA_VIEWS = {
  lateral:   new THREE.Vector3( 4.8,  0.5,  0.4),
  medial:    new THREE.Vector3(-3.8,  0.5,  0.4),
  superior:  new THREE.Vector3( 0.6,  5.5,  0.8),
  inferior:  new THREE.Vector3( 0.6, -5.5,  0.8),
  anterior:  new THREE.Vector3( 0.5,  0.5,  5.2),
  posterior: new THREE.Vector3( 0.5,  0.5, -5.6),
};

var camFrom = null, camTo = null, camT = 0;
var CAM_DUR = 0.72;

function setCameraView(name) {
  var tgt = CAMERA_VIEWS[name];
  if (!tgt) return;
  camFrom = camera.position.clone();
  camTo   = tgt.clone();
  camT    = 0;
  controls.target.copy(CAM_TARGET);
  document.querySelectorAll('.view-preset-btn').forEach(function(b) {
    b.classList.toggle('active', b.dataset.view === name);
  });
}

// ══════════════════════════════════════════════════════════════════════════════
// QUIZ-MODE REGION API
// ══════════════════════════════════════════════════════════════════════════════

function highlightRegion(regionId) {
  regionMeshes.forEach(function(m) {
    var match = m.userData.regionId === regionId;
    if (m.material.emissive) {
      m.material.emissive.set(match ? 0xd4a054 : 0x000000);
      m.material.emissiveIntensity = match ? 0.28 : 0;
    }
    m.material.opacity     = 1;
    m.material.transparent = false;
  });
}

function dimAllRegions(exceptIds) {
  exceptIds = exceptIds || [];
  regionMeshes.forEach(function(m) {
    var keep = exceptIds.indexOf(m.userData.regionId) !== -1;
    m.material.opacity     = keep ? 1.0 : 0.18;
    m.material.transparent = !keep;
    m.material.depthWrite  = keep;
  });
}

function resetRegions() {
  regionMeshes.forEach(function(m) {
    m.material.opacity     = 1;
    m.material.transparent = false;
    m.material.depthWrite  = true;
    _restoreColor(m);
  });
  selectedMesh = null;
  hoveredMesh  = null;
}

function toggleGlass(show) {
  glassVisible = (show === undefined) ? !glassVisible : !!show;
  if (glassMesh) glassMesh.visible = glassVisible;
  // When glass hides, reveal subcortical structures
  subcorticalMeshes.forEach(function(m) { m.visible = !glassVisible; });
}

function setSubcorticalVisible(show) {
  subcorticalMeshes.forEach(function(m) { m.visible = !!show; });
}

// ══════════════════════════════════════════════════════════════════════════════
// ANIMATION LOOP
// ══════════════════════════════════════════════════════════════════════════════

var animId = null;
var lastTs = 0;

function animate(ts) {
  animId = requestAnimationFrame(animate);
  var dt = Math.min((ts - lastTs) / 1000, 0.05);
  lastTs = ts;

  // Camera animation
  if (camTo) {
    camT = Math.min(camT + dt / CAM_DUR, 1);
    var e = 1 - Math.pow(1 - camT, 3);   // ease-out cubic
    camera.position.lerpVectors(camFrom, camTo, e);
    camera.lookAt(controls.target);
    if (camT >= 1) { camTo = null; controls.update(); }
  } else {
    controls.update();
  }

  // Hover detection (only visible, non-glass meshes)
  raycaster.setFromCamera(mouse, camera);
  var visibleRegions = regionMeshes.filter(function(m) { return m.visible; });
  var hits     = raycaster.intersectObjects(visibleRegions, false);
  var newHover = hits.length ? hits[0].object : null;
  if (newHover !== hoveredMesh) {
    setHover(newHover);
    canvas.style.cursor = newHover ? 'pointer' : 'grab';
  }

  renderer.render(scene, camera);
}

// ══════════════════════════════════════════════════════════════════════════════
// POINTER EVENTS
// ══════════════════════════════════════════════════════════════════════════════

var downPos = null;

canvas.addEventListener('pointermove', function(e) {
  var r = canvas.getBoundingClientRect();
  mouse.x =  ((e.clientX - r.left) / r.width)  * 2 - 1;
  mouse.y = -((e.clientY - r.top)  / r.height) * 2 + 1;
});

canvas.addEventListener('pointerdown', function(e) {
  canvas.style.cursor = 'grabbing';
  downPos = { x: e.clientX, y: e.clientY };
});

canvas.addEventListener('pointerup', function(e) {
  canvas.style.cursor = hoveredMesh ? 'pointer' : 'grab';
  if (!downPos) return;
  var dx = e.clientX - downPos.x;
  var dy = e.clientY - downPos.y;
  if (Math.sqrt(dx * dx + dy * dy) < 5) {
    var r = canvas.getBoundingClientRect();
    mouse.x =  ((e.clientX - r.left) / r.width)  * 2 - 1;
    mouse.y = -((e.clientY - r.top)  / r.height) * 2 + 1;
    raycaster.setFromCamera(mouse, camera);
    var visibleRegions = regionMeshes.filter(function(m) { return m.visible; });
    var hits = raycaster.intersectObjects(visibleRegions, false);
    selectRegion(hits.length ? hits[0].object : null);
  }
  downPos = null;
});

canvas.addEventListener('pointerleave', function() {
  mouse.set(-10, -10);
  setHover(null);
});

// ══════════════════════════════════════════════════════════════════════════════
// RESIZE
// ══════════════════════════════════════════════════════════════════════════════

var mountedContainer = null;

var resizeObserver = new ResizeObserver(function() {
  if (!mountedContainer) return;
  var w = mountedContainer.clientWidth;
  var h = mountedContainer.clientHeight || Math.round(w / 1.54);
  renderer.setSize(w, h);
  camera.aspect = w / h;
  camera.updateProjectionMatrix();
});

// ══════════════════════════════════════════════════════════════════════════════
// MOUNT / UNMOUNT
// ══════════════════════════════════════════════════════════════════════════════

function mount(container) {
  if (typeof container === 'string') container = document.querySelector(container);
  if (!container) return;
  if (mountedContainer === container) { if (!animId) animate(0); return; }
  if (mountedContainer) resizeObserver.unobserve(mountedContainer);
  mountedContainer = container;
  container.appendChild(canvas);
  resizeObserver.observe(container);
  // Immediately size the renderer so the first frame is correct
  var w = container.clientWidth  || window.innerWidth  - 256;
  var h = container.clientHeight || window.innerHeight - 52;
  renderer.setSize(w, h);
  camera.aspect = w / h;
  camera.updateProjectionMatrix();
  if (!animId) animate(0);
  setCameraView('lateral');
}

function unmount() {
  if (animId) { cancelAnimationFrame(animId); animId = null; }
  if (mountedContainer) {
    resizeObserver.unobserve(mountedContainer);
    if (canvas.parentNode === mountedContainer) mountedContainer.removeChild(canvas);
    mountedContainer = null;
  }
  hoveredMesh  = null;
  selectedMesh = null;
}

// ══════════════════════════════════════════════════════════════════════════════
// PUBLIC API
// ══════════════════════════════════════════════════════════════════════════════

window.__brain3d = {
  mount, unmount,
  setCameraView, CAMERA_VIEWS,
  highlightRegion, dimAllRegions, resetRegions,
  regionMeshes, corticalMeshes, subcorticalMeshes,
  toggleGlass, setSubcorticalVisible,
  ready: _readyPromise,
  // Compat stubs (from earlier version)
  setCsMode:         function() {},
  setCsSlider:       function() {},
  setVascTerritory:  function() {},
  toggleLesionMode:  function() {},
  resetLesions:      function() {},
  activatePathology: function() {},
  clearPathology:    function() {},
  PATHOLOGY_DEFS:    {},
  showPathway:       function() {},
  hidePathway:       function() {},
  setPathway:        function() {},
};

// Auto-mount: try #brain-stage (new explorer layout) then #brain-container-3d (legacy).
var _c = document.getElementById('brain-stage') || document.getElementById('brain-container-3d');
if (_c) mount(_c);
